#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "done haproxy"

server_config=\
"
frontend abdallah_frontend
        bind *:80
        mode http
        default_backend abdallah_backend
backend abdallah_backend
        balance roundrobin
        server 516892-web-01 54.85.96.172:80 check
        server 516892-web-02 54.210.130.17:80 check
"

echo "haproxy is configured now..."

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo "    Done"

echo 'Testing the HAproxy configuration file...'
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

echo "Restarting the HAProxy service..."

sudo service haproxy restart

echo 'Thank, should now all work'
