#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.
file=$(date +"%d-%m-%Y")
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$file".tar.gz backup.sql
