#!/usr/bin/env bash
# Write Bash (init) script 101-manage_my_process that manages manage_my_process. (both files need to be pushed to git)

pid_file="/var/run/my_process.pid"

if [ $# -gt 0 ]; then
	case "$1" in
		start)
			./manage_my_process &
			echo "$!" > "$pid_file"
			echo "manage_my_process started"
			;;
		stop)
			kill "$(cat "$pid_file")"
			rm -f "$pid_file"
			echo "manage_my_process stopped"
			;;
		restart)
			kill "$(cat "$pid_file")"
			rm -f "$pid_file"
			./manage_my_process &
			echo "$!" > "$pid_file"
			echo "manage_my_process restarted"
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
			;;
	esac
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
