#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i=0
while [ $i -le 12 ]
do
    n=1
    echo "Hour: $i"
    while [ $n -le 59 ]
    do
        echo $n
        ((n++))
    done
    ((i++))
done
