#!/usr/bin/env bash
# Write a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

i="$(pwd)"
dir="$(ls "$i")"
for file in $dir
do
    echo "$file" | cut -d '-' -f 2-
done

# 100-read_and_cut
# 101-tell_the_story_of_passwd
# 102-lets_parse_apache_logs
# 103-dig_the-data
# 10-fizzbuzz
# 1-for_best_school
# 2-while_best_school
# 3-until_best_school
# 4-if_9_say_hi
# 5-4_bad_luck_8_is_your_chance
# 6-superstitious_numbers
# 7-clock
# 8-for_ls
# 9-to_file_or_not_to_file
# README.md
