#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements
# localhost     => to 127.0.0.2
# facebook.com  => to 8.8.8.8

cp /etc/hosts ~/hosts
echo "127.0.0.2		localhost" > ~/hosts
echo "8.8.8.8		facebook.com" >> ~/hosts
cp -f ~/hosts /etc/hosts
