#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080' /etc/nginx/sites-available/default
if pgrep nginx >/dev/null; then
	sudo service nginx restart
else
	sudo service nginx start
fi
